# example_config.yml — semScreenR
preset: balanced            # conservative | balanced | aggressive

gates:                      # acceptance gates for changes
  min_delta:
    CFI:   0.005
    TLI:   0.005
    RMSEA: -0.005
    SRMR:  -0.005
  use_validation: true
  validation_k: 5
  perfect_fit_guard: true

limits:                     # global caps and minima
  max_row_drop_frac:   0.10
  max_item_drop_frac:  0.10
  min_n:               200
  min_items_per_factor: 3
  max_iterations:       5

thresholds:                 # item-level rules
  loading_min: 0.40         # drop candidates if loading < this
  max_mod_index: null       # reserved

careless:                   # careless-responding screen
  items: []                 # e.g., ["x1","x2","x3"]
  rt_col: null              # e.g., "rt_ms"
  longstring_k: 10
  irv_min: 0.15
  mahal_p: 0.001
  fast_q: 0.02
  max_row_drop_frac_cr: 0.05
