#' Export a compact HTML report with pre/post fit and action log
#'
#' If gt is available, includes an APA-like fit table. Otherwise plain HTML.
#'
#' @param dat data
#' @param model model syntax
#' @param res result from triage_apply
#' @param file output .html file path
#' @return normalized file path (invisible)
#' @export
export_sem_report <- function(dat, model, res, file = "sem_report.html") {
  if (!inherits(res, "semScreen_result")) {
    stop("res must be a semScreen_result object from triage_apply()")
  }
  pre  <- res$fit$pre  %||% list()
  post <- res$fit$post %||% list()

  # Generate fit table HTML
  table_html <- ""
  tryCatch({
    tb <- apa_fit_table(pre, post)
    if (.pkg_available("gt") && inherits(tb, "gt_tbl")) {
      table_html <- gt::as_raw_html(tb)
    } else {
      # Simple fallback table
      df <- as.data.frame(tb)
      if (nrow(df) > 0) {
        rows <- apply(df, 1, function(r) {
          cells <- sapply(r, function(x) {
            if (is.na(x)) "—" else format(x, digits = 3)
          })
          paste0("<tr>", paste0(sprintf("<td>%s</td>", cells), collapse=""), "</tr>")
        })
        header <- paste0("<tr>", paste0(sprintf("<th>%s</th>", names(df)), collapse=""), "</tr>")
        table_html <- paste0(
          "<table border='1' style='border-collapse: collapse; width: 100%;'>",
          header, 
          paste0(rows, collapse=""), 
          "</table>"
        )
      } else {
        table_html <- "<p>No fit measures available.</p>"
      }
    }
  }, error = function(e) {
    table_html <<- paste0("<p>Error generating fit table: ", e$message, "</p>")
  })

  # Generate action log
  hist_html <- ""
  tryCatch({
    if (length(res$history) == 0) {
      hist_html <- "<p>No actions were taken during screening.</p>"
    } else {
      hist_items <- sapply(res$history, function(x) {
        paste0(
          "<li><strong>Step ", x$step, ":</strong> ",
          x$type, 
          if (!is.null(x$item)) paste0(" (", x$item, ")") else "",
          " - ", x$note %||% "No details",
          "</li>"
        )
      })
      hist_html <- paste0("<ul>", paste0(hist_items, collapse=""), "</ul>")
    }
  }, error = function(e) {
    hist_html <- paste0("<p>Error generating action log: ", e$message, "</p>")
  })
  
  # Generate summary statistics
  summary_html <- tryCatch({
    paste0(
      "<ul>",
      "<li><strong>Status:</strong> ", res$status, "</li>",
      "<li><strong>Original sample size:</strong> ", nrow(dat), "</li>",
      "<li><strong>Final sample size:</strong> ", nrow(res$data_final), "</li>",
      "<li><strong>Actions taken:</strong> ", length(res$history), "</li>",
      if (length(pre) > 0 && !is.null(pre$cfi)) {
        paste0("<li><strong>Pre-screening CFI:</strong> ", 
               sprintf("%.3f", pre$cfi %||% NA), "</li>")
      } else "",
      if (length(post) > 0 && !is.null(post$cfi)) {
        paste0("<li><strong>Post-screening CFI:</strong> ", 
               sprintf("%.3f", post$cfi %||% NA), "</li>")
      } else "",
      "</ul>"
    )
  }, error = function(e) {
    paste0("<p>Error generating summary: ", e$message, "</p>")
  })

  # Create complete HTML document
  html <- c(
    "<!DOCTYPE html>",
    "<html><head>",
    "<meta charset='utf-8'>",
    "<title>semScreenR Report</title>",
    "<style>",
    "body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 2rem; }",
    "h1, h2 { margin: 1rem 0 0.5rem 0; color: #333; }",
    "table { border-collapse: collapse; width: 100%; margin: 1rem 0; }",
    "th, td { border: 1px solid #ddd; padding: 0.5rem; text-align: left; }",
    "th { background: #f5f5f5; font-weight: bold; }",
    "ul { margin: 0.5rem 0; }",
    "li { margin: 0.25rem 0; }",
    ".alert { padding: 1rem; margin: 1rem 0; border-radius: 4px; }",
    ".alert-info { background: #d1ecf1; border: 1px solid #bee5eb; color: #0c5460; }",
    "</style>",
    "</head><body>",
    "<h1>semScreenR Analysis Report</h1>",
    
    "<h2>Summary</h2>",
    summary_html,
    
    "<h2>Model Fit Comparison</h2>",
    table_html,
    
    "<h2>Action Log</h2>",
    hist_html,
    
    "<div class='alert alert-info'>",
    "<strong>Note:</strong> This report was generated by semScreenR. ",
    "All screening decisions were made using pre-registered rules and validation procedures. ",
    "For reproducibility, please cite your screening parameters in any publications.",
    "</div>",
    
    "<hr>",
    "<p><small>Generated on ", Sys.time(), " using semScreenR version ", 
    utils::packageVersion("semScreenR") %||% "unknown", "</small></p>",
    
    "</body></html>"
  )

  # Write file with error handling
  tryCatch({
    writeLines(html, file)
    message("Report exported to: ", normalizePath(file))
  }, error = function(e) {
    stop("Failed to write report file: ", e$message)
  })
  
  invisible(normalizePath(file))
}